### ISSUE TITLE
Cannot create a datasource with this plugin via Grafana Provisioning

### ISSUE THREAD

**Issue by loki-dv** [G-Core/cdn-stats-datasource-plugin#7]
Hello.
We are using the [Grafana Provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/) mechanism to provisioning of our Grafana instance. Syntax is pretty close to your example in README but for some reasons we have issues with putting token into database.

Example of configuration:

```
  - name: "cdn-stats-test2"
    orgId: 1
    editable: true
    access: "proxy"
    type: "gcorelabs-cdn-stats-datasource"
    version: 1
    jsonData:
      apiUrl: "api.gcore.com"
    secureJsonData: 'APIKey 0123$abcdefghij'
```

Of course, we created a token correctly. Tried with APIKey word and without it, with quotes and without - no result. Behaviour in the end is: when we try to query on this datasource we see "Invalid API token" (with APIKey word) or "Authentication credentials were not provided" (without it) errors.

Interesting that if we edit the datasource manually and just put the token (without any prefixes and words) it works! What is the right way to configure the datasource in the provisioning process?

Thanks.

If it is important:

```
grafana-server --version
Version 10.0.9 (commit: 439bbb4722, branch: HEAD)
```
